### PR TITLE
Add MLP code

### PR DESCRIPTION
**Pull request by emohat1r**
Add basic code for MLP. Code style to be discussed.

### CODE REVIEW

**Comment by emohat1r** [comment]
I was thinking, that people might prefer to do dropout in, let's say, the first 2 layers and not type 0.0 for other 10, which is why I left it like that. What do you think about it?

**Comment by timbmg** [comment]
It will break the code though because you are looping over `sizes`, so if `biases` or `dropouts` is smaller than sizes, you'll get index out of range. If you account for that, I think its a good idea. 

I was thinking the easiest way to do this would be maybe before you populate the `layers` list, create the `biases` and `dropouts` lists. So something like this:
```
if isinstance(biases, bool):
    biases = [biases] * len(sizes)-1
elif isinstance(biases, list):
    biases.extend([True] * len(sizes)-1)
```

**Comment by AashishV** [comment]
How did you test the MLP component? 
Please correct me if I am wrong, the list of dropouts, biases and sizes are of different sizes?
Can there be an example script which can help others how to use it? This should include all the options for the component.
I am asking this because this is just MLP and it is getting complicated as how to use it. Also, are we going to use this component for a simple linear?

**Comment by timbmg** [comment]
If you only have one linear layer (plus activation function), there's no need to use it.

We could add an example in the doc string as done in the pytorch docs, but I think this should rather show a simple use case. However, from the docstring it should become clear how to use this class. So maybe we can improve there?

About testing would be best to have unit tests. But these wont really help you understand, but rather will check that its correct (e.g. return expected result/object, errors, etc.)

**Comment by AashishV** [comment]
Yep, that works too. Right now, I have to dig through the code to understand the format of input arguments.

**Comment by timbmg** [comment]
@AashishV object types of the arguments are already in the docstring (github is just hiding it since there has been no change, but you can expand it on the left hand side).

@emohat1r could you add then the following:
- Adapt docstring such that smaller biases and dropouts list functionalty is explained
- Add small example to docstring
- Test cases: 
    check if value error is raised when len(biases) > len(sizes) - 1
    check if value error is raised when len(dropouts) > len(sizes) - 2
    check if correct sequential object is created for passing some usual paramameters

If there's any other test case you can think of, go ahead of course :)

For  the test cases would be best to create a test folder on the top level.

**Comment by emohat1r** [comment]
@timbmg @AashishV Is there any specific format for a docstring, that I can use as a reference?
Also, should tests be done in a proper testing framework or just code with asserts?

**Comment by AashishV** [comment]
For documentation, I think Elia had i-machine sort of documentation, https://i-machine-think.github.io/machine/build/html/index.html. But, I am not sure what is the template of the docstring they use to generate the documentation.

**Comment by timbmg** [comment]
About the docstring, the [sphinx documentation](https://pythonhosted.org/an_example_pypi_project/sphinx.html) has all the formats that it supports. But we still have to define how to use them. But let's do that at a later point. 

For the tests, please use pythons unittest library ([here's a basic example](https://docs.python.org/3/library/unittest.html#basic-example)). We should put all the files in a top level folder called `test` and there you can create a file called `test_components` with the test class.

**Comment by emohat1r** [comment]
Okay, I will implement tests today.
The other thing we can use is standard Sphinx docstring: http://daouzli.com/blog/docstring.html

**Comment by timbmg** [comment]
Lets go with the GoogleDoc one: http://daouzli.com/blog/docstring.html#googledoc

No, activation function should always be there. But we can make it default to ReLU.

**Comment by emohat1r** [comment]
@timbmg @AashishV Do you know by any chance how to compare two models in pytorch? Just to check that their layers are the same?

**Comment by timbmg** [comment]
The best I can come up with at the top of my head is that you loop over the parameters and check its sizes:
```python
p_sizes = [ (10, 5), (5), (5, 2) ]
for i, p in enumerate(mlp.parameters()):
    assertTrue(p.size() == torch.Size(p_sizes[i]))
```

**Comment by emohat1r** [comment]
Sorry, PyCharm accidentally reformatted all the files. Just take a look at the MLP and unit test file though - other files should not be different content-wise.

**Pull request merged**
